apiVersion: v1
kind: Secret

metadata:
  name: db-secret
  namespace: devops-exam

type: Opaque

stringData:

  DB_HOST: "exam-platform-db.cwb6qummqfvq.us-east-1.rds.amazonaws.com"

  DB_PORT: "3306"

  DB_NAME: "exam-platform-db"

  DB_USER: "admin"

  DB_PASSWORD: "Rishav13!"
